// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiqX-4ZwC382gZG4iQk1n-45R7sQKoYPE',
    appId: '1:510480483026:web:82e1734d57c4df6e28a30b',
    messagingSenderId: '510480483026',
    projectId: 'lmsproject-2ece8',
    authDomain: 'lmsproject-2ece8.firebaseapp.com',
    storageBucket: 'lmsproject-2ece8.firebasestorage.app',
    measurementId: 'G-WDLJS70X7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXRXj8JXrDZ8MJYAV_H8dAFGkg8JvQZok',
    appId: '1:510480483026:android:d5a9ac9fd2dbac6e28a30b',
    messagingSenderId: '510480483026',
    projectId: 'lmsproject-2ece8',
    storageBucket: 'lmsproject-2ece8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5QEWa9WwZHjdEkH-6RheaMGpxlo_95vc',
    appId: '1:510480483026:ios:7edb62c2cf12268b28a30b',
    messagingSenderId: '510480483026',
    projectId: 'lmsproject-2ece8',
    storageBucket: 'lmsproject-2ece8.firebasestorage.app',
    androidClientId: '510480483026-jj90snl41p4os62m49ajd2qkdlstrnbv.apps.googleusercontent.com',
    iosClientId: '510480483026-d3541kqol9kqv0lajet045qiasvvj0jk.apps.googleusercontent.com',
    iosBundleId: 'com.exmaple.SCRIPTS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5QEWa9WwZHjdEkH-6RheaMGpxlo_95vc',
    appId: '1:510480483026:ios:e3a94be6853e7ba928a30b',
    messagingSenderId: '510480483026',
    projectId: 'lmsproject-2ece8',
    storageBucket: 'lmsproject-2ece8.firebasestorage.app',
    androidClientId: '510480483026-jj90snl41p4os62m49ajd2qkdlstrnbv.apps.googleusercontent.com',
    iosClientId: '510480483026-9nbltadapkjq020mpfkahulmsim018rh.apps.googleusercontent.com',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiqX-4ZwC382gZG4iQk1n-45R7sQKoYPE',
    appId: '1:510480483026:web:c4ad0197e3fc8aa228a30b',
    messagingSenderId: '510480483026',
    projectId: 'lmsproject-2ece8',
    authDomain: 'lmsproject-2ece8.firebaseapp.com',
    storageBucket: 'lmsproject-2ece8.firebasestorage.app',
    measurementId: 'G-1YQ1L2C8QC',
  );
}
